//   ,:.
//  (:::) Script
//   `-'
// Generated by GuavaScript (guavac) v0.1
// Last modified: 5/27/2016, 2:18:56 AM
var gulp = require("gulp");
var plugins = require("gulp-load-plugins");
var runSequence = require("run-sequence");
var rm = require("del");
var pkg = require("./package.json");
var dirs = pkg.directories;
var libs = pkg.libraries;
gulp.task("clean", function () {
	rm([dirs.dist]);
});
gulp.task("copy", [
	"copy:html",
	"copy:css",
	"copy:js",
	"copy:img"
]);
gulp.task("copy:html", function () {
	gulp.src(dirs.src + "/*.html").pipe(plugins().replace(/{{JQUERY_VERSION}}/g, libs.jquery.version)).pipe(plugins().replace(/{{VERSION}}/g, pkg.version)).pipe(gulp.dest(dirs.dist));
});
gulp.task("copy:css", function () {
	gulp.src([
		dirs.src + "/css/**/*.css",
		"!" + dirs.src + "/css/vendor/*.css"
	]).pipe(plugins().autoprefixer({
		browsers: [
			"last 2 versions",
			"not ie < 11"
		]
	})).pipe(gulp.dest(dirs.dist + "/css"));
	gulp.src([dirs.src + "/css/vendor/*.css"]).pipe(gulp.dest(dirs.dist + "/css/vendor"));
});
gulp.task("copy:js", function () {
	gulp.src(dirs.src + "/js/**/*.js").pipe(gulp.dest(dirs.dist + "/js"));
});
gulp.task("copy:img", function () {
	gulp.src([
		dirs.src + "/img/**/*.png",
		dirs.src + "/img/**/*.jpg"
	]).pipe(gulp.dest(dirs.dist + "/img"));
	gulp.src(dirs.factorio + "/icons/*.png").pipe(gulp.dest(dirs.dist + "/img/icons"));
});
gulp.task("build", function () {
	runSequence("copy");
});
gulp.task("default", ["build"]);